# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b08dbad0358c1742a027fa0de80421c7dabb799955a704df4a272e68ce776d949f865ed5fd324f9075f2a54abfb2d6b612c51473bc0d0edf544cf20c3f503936

test:
  secret_key_base: 920ef5b184b1ccefe74cbf5458d26679ead4df109b7562747f11a86872624f9057fc2ca7268a91ae996d41500b65bfb07ba89bae9494cbdbaa7ae53bbb2aa0fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
